//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attempt()
        {
            this.Attempt_Question = new HashSet<Attempt_Question>();
        }
    
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> TestId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Test Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attempt_Question> Attempt_Question { get; set; }
    }
}
